Repository Team-Pickify/Pickfy-FE, pull requests merged in 2025-02, with the labels that each got.

#43 🚨 Hotfix: 헤더 고정 및 스플래시 속 로고파일 수정
  src/assets/whiteLogo.png
  src/layouts/navbar.jsx
  src/pages/splash/splashScreen.jsx
Labels: 🐛BugFix

#44 ✨ Feat: axios 객체 생성
  src/apis/axiosInstance.js
  src/pages/admin/magazine/MangeMagazine.jsx
Labels: 📬API

#48 🚨 Hotfix: AddressBox 파일명 앞에 공백으로 인한 오류 해결
  src/components/admin/AddressBox.jsx
  src/pages/admin/place/AddPlace.jsx
  src/pages/admin/place/FixPlace.jsx
Labels: 🐛BugFix

#53 axiosInstance수정
  src/apis/axiosInstance.js
  src/components/InfoSmall.jsx
Labels: 🐛BugFix

#55 마이플레이스 리스트 수정
  src/apis/axiosInstance.js
  src/components/Info.jsx
  src/components/InfoSmall.jsx
  src/pages/placeList/index.jsx
Labels: 🐛BugFix

#60 🐛 Fix: 처음 페이지 접속 시 로그인 페이지로 이동하게 하는 코드 주석 해제
  yarn.lock
Labels: ♻️Refactor

#65 🐛 Fix: 토큰을 쿠키로 관리하기 위해 http->https로 연결되게 변경
  .gitignore
  src/pages/setting/index.jsx
  vite.config.js
Labels: 🐛BugFix

#66 ✨ Feat: 설정 페이지 API 연동 완료
  src/components/Linkbox.jsx
  src/hooks/useUserInfo.jsx
  src/pages/setting/index.jsx
Labels: ✨Feature, 📬API

#70 ✨feat: 공유하기 기능 추가
  dev-dist/sw.js
  src/components/modal/shareUrl.jsx
Labels: ✨Feature

#78 ✨ Feat: 관리자 로그인 시 설정 페이지에 관리자 페이지 이동 옵션 추가
  dev-dist/sw.js
  package-lock.json
  src/pages/admin/index.jsx
  src/pages/login/admin-login.jsx
  src/pages/login/login.jsx
  src/pages/setting/index.jsx
  vite.config.js
  yarn.lock
Labels: ✨Feature

#81 ✨마이 플레이스리스트 api연결 수정
  dev-dist/sw.js
  src/components/Info.jsx
  src/components/categoryBtn.jsx
Labels: 📬API

#88 🐛 Fix: API URL 올바르게 수정
  dev-dist/sw.js
  src/components/categoryBtn.jsx
  src/pages/admin/place/AddPlace.jsx
  src/pages/login/admin-login.jsx
  src/pages/login/login.jsx
Labels: 🐛BugFix, 📬API

#91 🐛 Fix: 배경 높이 늘림
  dev-dist/sw.js
  src/pages/admin/magazine/MangeMagazine.jsx
  src/pages/admin/place/ManagePlace.jsx
Labels: 🐛BugFix, 💄UI

#100 length 에러 수정
  src/components/Info.jsx
  src/components/InfoSmall.jsx
  src/components/categoryBtn.jsx
  src/pages/placeList/index.jsx
Labels: 🐛BugFix

#102 fix: 배포 문제해결 되어라..
  dev-dist/sw.js
  src/components/categoryBtn.jsx
  vite.config.js
Labels: 🐛BugFix

#105 fix: 오타임
  src/components/categoryBtn.jsx
Labels: 🐛BugFix

#106 main 브랜치 merge
  src/components/categoryBtn.jsx
  src/pages/admin/place/ManagePlace.jsx
Labels: 🐛BugFix

#107 🐛fix:useEffect로 갱신
  src/components/Info.jsx
Labels: 🐛BugFix

#111 🐛하트 토글 저장로직
  dev-dist/sw.js
  index.html
  src/assets/cafe1.png
  src/assets/cafe2.png
  src/assets/cafe3.png
  src/assets/cafe4.png
  src/assets/cafe5.png
  src/components/Info.jsx
  src/components/InfoSmall.jsx
  src/components/carousel/Carousel.jsx
  src/pages/placeList/index.jsx
Labels: 🐛BugFix

#113 ✨ Feat: 관리자 페이지 페이지네이션 추가
  dev-dist/sw.js
  src/pages/admin/place/ManagePlace.jsx
Labels: ✨Feature, 💄UI
